spring.application.name=games

spring.datasource.url=jdbc:h2:mem:games
spring.datasource.username=RiSa
spring.datasource.password=risajava

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update